/* Content for the UtilityAI Pro overview. Sourced from the Southern Company SOW (Sep 2026)
   and the Con Edison enterprise proposal (Sep 2026), generalized for any utility. */

// Target environments: a cloud plus the data lake the utility already runs.
const CLOUDS = {
  azure: { label: "Azure", compute: "Azure confidential containers / confidential VMs", identity: "Entra ID + your customer SSO",
    network: "Azure Private Link", agentsExt: "Azure AI Foundry", bi: "Looker app (native) or Power BI",
    native: { label: "Microsoft Fabric", data: "Microsoft Fabric / ADLS Gen2, governed with Purview", dataShort: "Fabric · Purview", jobs: "Fabric Spark jobs", agentsInt: "Microsoft Copilot" } },
  gcp: { label: "Google Cloud", compute: "Confidential GKE nodes / Confidential VMs", identity: "Cloud Identity + your customer SSO",
    network: "Private Service Connect", agentsExt: "Vertex AI Agent Builder", bi: "Looker",
    native: { label: "BigQuery", data: "BigQuery datasets, governed with Dataplex", dataShort: "BigQuery · Dataplex", jobs: "Dataproc / BigQuery jobs", agentsInt: "Gemini Enterprise" } },
  aws: { label: "AWS", compute: "EC2 with Nitro Enclaves", identity: "IAM Identity Center + your customer SSO",
    network: "AWS PrivateLink", agentsExt: "Amazon Bedrock Agents", bi: "Looker or QuickSight",
    native: { label: "AWS-native", data: "S3 + Redshift, governed with Lake Formation", dataShort: "Redshift · Lake Formation", jobs: "EMR / Glue jobs", agentsInt: "Amazon Q" } },
  oci: { label: "Oracle Cloud", compute: "OCI Confidential Computing", identity: "OCI IAM + your customer SSO",
    network: "OCI private endpoints", agentsExt: "OCI Generative AI Agents", bi: "Oracle Analytics Cloud or Looker",
    native: { label: "Oracle ADW", data: "Autonomous Data Warehouse + Object Storage", dataShort: "ADW · Object Storage", jobs: "OCI Data Flow jobs", agentsInt: "Microsoft Copilot / OCI Generative AI" } },
};
const LAKES = {
  databricks: { label: "Databricks", data: "Databricks Delta tables, governed in Unity Catalog", dataShort: "Delta · Unity Catalog", jobs: "Databricks Workflows (PySpark)", agentsInt: "Databricks Agent Bricks (Genie)" },
  snowflake: { label: "Snowflake", data: "Snowflake tables, governed with Horizon", dataShort: "Snowflake · Horizon", jobs: "Snowpark jobs + Tasks", agentsInt: "Snowflake Cortex Agents",
    computeAlt: "or Snowpark Container Services" },
  native: { label: "Cloud-native lake" },
};

const NODES = {
  // Utility data sources
  "s-ami":   { band: "found", row: "src", name: "AMI interval data", sub: "15-min or hourly reads", kind: "Your data set",
    desc: "Historical and incremental interval reads, the primary model input. Bidgely uses finer input granularity where available and publishes appliance outputs at a minimum of one hour.",
    feeds: "Input builders" },
  "s-bill":  { band: "found", row: "src", name: "Billing & CIS", sub: "accounts, bill cycles", kind: "Your data set",
    desc: "Account, premise and bill-cycle data. Bill cycles drive itemization and bill projection timing.", feeds: "Input builders, Rate engine" },
  "s-rate":  { band: "found", row: "src", name: "Rate catalog", sub: "tariffs, TOU windows", kind: "Your data set",
    desc: "Tariff definitions loaded through the Control Center. Powers cost views, bill projection and rate comparison.", feeds: "Rate engine, Rate comparison" },
  "s-wx":    { band: "found", row: "src", name: "Weather", sub: "hourly temperature", kind: "Your data set",
    desc: "Temperature by weather station or zip. Separates weather-driven heating and cooling from behavior.", feeds: "Disaggregation, bill explanations" },
  "s-prog":  { band: "found", row: "src", name: "Programs & events", sub: "EE, DR, rate enrollment", kind: "Your data set",
    desc: "Enrollment and event history for efficiency, demand response and rate programs. Used to exclude participants, measure response and target cross-sell.", feeds: "Analytics Workbench, flexibility engines" },
  "s-gis":   { band: "found", row: "src", name: "GIS & topology", sub: "feeder, transformer, network", kind: "Your data set",
    desc: "Meter-to-asset mapping. Lets end-use outputs roll up to the network, feeder and transformer levels planners work in.", feeds: "Meter-to-asset aggregation" },
  "s-survey":{ band: "found", row: "src", name: "Home profile surveys", sub: "CSR and self-reported", kind: "Your data set",
    desc: "Answers captured by customers or CSRs about the home. Improves personalization of disaggregation for that premise.", feeds: "Disaggregation, Personalized insights" },
  "s-ext":   { band: "found", row: "src", name: "External data", sub: "census, permits, housing", kind: "Your data set",
    desc: "Public and licensed data such as census income distribution, building permits and housing stock. Joined with model outputs in your platform.", feeds: "Customer income, forecasting" },

  // Data layer
  "d-in":    { band: "found", row: "lake", name: "Input builders", sub: "{jobs}", kind: "Bidgely data layer",
    desc: "Assemble AMI, billing, enrollment and ground truth into validated, model-ready batches on configurable triggers, with data sufficiency and sanity checks." },
  "d-out":   { band: "found", row: "lake", name: "Governed output tables", sub: "{dataShort}", kind: "Bidgely data layer",
    desc: "Model inference results land as governed tables in your catalog on every run, under your access controls and lineage." },
  "d-cdl":   { band: "found", row: "lake", name: "Complete Data Layer", sub: "single source of truth", kind: "Bidgely data layer",
    desc: "Model outputs enriched by rate data and engine results. Every dashboard, API, agent and email reads from here, so every channel shows the same numbers." },
  "d-promo": { band: "found", row: "lake", name: "Promotion pipelines", sub: "scheduled batch or CDC", kind: "Bidgely data layer",
    desc: "Publish the relevant slices of the Complete Data Layer into the application tier behind the APIs and MCP servers. Scheduled refresh, with change data capture for high-velocity segments." },

  // Models
  "m-disagg":{ band: "models", name: "Appliance & DER disaggregation", sub: "hourly · 12 categories", kind: "Bidgely model", tab: "disagg",
    desc: "Detects appliance and DER ownership and usage from meter data: always on, heating, cooling, water heating, refrigeration, lighting, pool pumps, EV charging and solar at hourly granularity, plus cooking, laundry and entertainment monthly." },
  "m-attr":  { band: "models", name: "Appliance & DER attributes", sub: "fuel, heat pump, charger kW", kind: "Bidgely model", tab: "attr",
    desc: "Profiles each detected appliance: heating fuel type, heat pump presence, pool pump type, EV charger amplitude, solar capacity, smart thermostat and battery detection." },
  "m-ineff": { band: "models", name: "Appliance inefficiency", sub: "HVAC degradation", kind: "Bidgely model", tab: "ineff",
    desc: "Finds heating and cooling equipment that is degrading, short cycling or saturating, from AMI data alone." },
  "m-life":  { band: "models", name: "Customer lifestyle", sub: "archetypes", kind: "Bidgely model", tab: "life",
    desc: "Clusters seasonal and daily usage into archetypes such as Dormant, Office Goer, Active and Weekend Warrior." },
  "m-prop":  { band: "models", name: "DER propensity", sub: "EV · solar likelihood", kind: "Bidgely model", tab: "prop",
    desc: "Scores each customer's likelihood of adopting an EV or installing solar." },
  "m-inc":   { band: "models", name: "Customer income", sub: "premise-level LMI", kind: "Bidgely model", tab: "inc",
    desc: "Estimates the likelihood a household is income eligible, from its energy profile combined with public income distribution data." },
  "m-pi":    { band: "models", name: "Personalized insights", sub: "similar-home comparison", kind: "Bidgely model", tab: "pi",
    desc: "Compares each home against statistically similar homes on total and appliance-level usage, and ranks the savings tips that matter for that home." },
  "m-rev":   { band: "models", name: "Revenue loss", sub: "theft · tamper · misuse", kind: "Bidgely model", tab: "rev",
    desc: "Detects and categorizes anomalies: theft, rate misuse, tampering, load violation, power factor and terminal burn." },

  // Engines
  "e-agg":   { band: "engines", group: "Grid & analytics", name: "Meter-to-asset aggregation", sub: "feeder · network 8760s", kind: "Bidgely engine",
    desc: "Rolls hourly end-use outputs from each meter up your GIS hierarchy into 8760 load shapes per transformer, feeder and network." },
  "e-flex":  { band: "engines", group: "Grid & analytics", name: "Flexible load calculation", sub: "shiftable kW by hour", kind: "Bidgely engine",
    desc: "Sizes each customer's shiftable kW hour by hour inside your event windows from EV, HVAC, pool, water heating and battery loads." },
  "e-fc":    { band: "engines", group: "Grid & analytics", name: "Forecast heuristics", sub: "adoption & growth inputs", kind: "Bidgely engine",
    desc: "Turns adoption trends and propensity scores into inputs for your short, medium and long-term forecasting models." },
  "e-kw":    { band: "engines", group: "Grid & analytics", name: "Demand kW processing", sub: "kWh to kW", kind: "Bidgely engine",
    desc: "Computes kW demand values from AMI kWh intervals, for demand charges, peak analysis and design criteria." },
  "e-rate":  { band: "engines", group: "Customer experience", name: "Rate engine", sub: "sub-cycle cost", kind: "Bidgely engine",
    desc: "Models your rate plans to cost any usage at hourly, daily or weekly granularity, forward-looking or historical. Can also connect to your existing rate engine." },
  "e-cost":  { band: "engines", group: "Customer experience", name: "Usage & cost aggregations", sub: "day · month · TOU band", kind: "Bidgely engine",
    desc: "Aggregates usage and cost by day, month and rate dimension such as TOU periods." },
  "e-bp":    { band: "engines", group: "Customer experience", name: "Bill projection", sub: "in-cycle forecast", kind: "Bidgely engine",
    desc: "Forecasts the cost of the current, incomplete billing cycle." },
  "e-rc":    { band: "engines", group: "Customer experience", name: "Rate comparison", sub: "best-fit plan", kind: "Bidgely engine",
    desc: "Compares a customer's actual interval usage across every rate plan they are eligible for." },
  "e-rec":   { band: "engines", group: "Customer experience", name: "Recommendations", sub: "ranked savings tips", kind: "Bidgely engine",
    desc: "Generates a ranked list of relevant savings tips for each customer and billing cycle." },
  "e-hi":    { band: "engines", group: "Customer experience", name: "Hyper Insights", sub: "habits & opportunities", kind: "Bidgely engine",
    desc: "Computes deeper insights into usage habits, inefficiencies and savings opportunities." },

  // Interfaces
  "i-api":   { band: "engines", group: "APIs, MCPs & apps", name: "CX APIs", sub: "14 REST endpoints", kind: "Bidgely interface",
    desc: "Ratepayer-scoped REST endpoints: usage and disaggregation, bill itemization, bill projection, rate comparison, similar homes, recommendations, surveys, program participation, billing history and Hyper Insights. Served from a thin data-access layer behind your identity and API gateway." },
  "i-mcp":   { band: "engines", group: "APIs, MCPs & apps", name: "MCP servers", sub: "Energy Assistant · Agentic Tools · IVR", kind: "Bidgely interface",
    desc: "Model Context Protocol servers expose standardized tools any agent platform can call: Energy Assistant, Analyze My Bill, Find the Best Rate, EV ROI, PV ROI, Home Bill Optimizer and IVR Agent." },
  "i-awb":   { band: "engines", group: "APIs, MCPs & apps", name: "Analytics Workbench", sub: "{bi}", kind: "Bidgely application",
    desc: "Segmentation and targeting for DSM, marketing and grid teams: build and publish segments, compare demand curves, map EV, solar and LMI concentration, simulate programs and export lists. Reads directly from the Complete Data Layer." },
  "i-ea":    { band: "engines", group: "APIs, MCPs & apps", name: "Energy Analyst agent", sub: "on {agentsInt}", kind: "Bidgely agent",
    desc: "A GenAI agent that answers plain-language questions with governed queries over the Complete Data Layer, and returns explained, data-grounded answers." },
  "i-cc":    { band: "engines", group: "APIs, MCPs & apps", name: "Control Center", sub: "config · triggers · content", kind: "Bidgely interface",
    desc: "Configure each component, manage tips and program content, set schedules and alert thresholds, and update the rate catalog." },

  // Channels & agents
  "o-web":   { band: "out", name: "Web & mobile app", sub: "your portal", kind: "You own",
    desc: "Your portal renders appliance breakdowns, bill explanations and rate tools from the CX APIs, in your brand, starting from Bidgely reference widgets." },
  "o-email": { band: "out", name: "Email, alerts & HERs", sub: "your send platform", kind: "You own",
    desc: "Monthly summaries, high bill alerts and home energy reports populated from the data layer and sent through your email and print vendors." },
  "o-ivr":   { band: "out", name: "IVR & voice", sub: "call deflection", kind: "You own",
    desc: "Your IVR answers high bill, rate and similar-home questions through the IVR Agent MCP before the call reaches a representative." },
  "o-chat":  { band: "out", name: "Chat & customer agents", sub: "{agentsExt}", kind: "You own",
    desc: "Your customer-facing agent calls Bidgely MCP tools as a sub-agent. Evals, guardrails and brand voice stay in your platform." },
  "o-csr":   { band: "out", name: "CSR desktop", sub: "high bill · survey widget", kind: "You own",
    desc: "Representatives see the same bill explanation the customer saw, plus an Energy Assistant view and the home profile survey widget." },
  "o-ai":    { band: "out", name: "Internal AI tools", sub: "{agentsInt}", kind: "You own",
    desc: "Your enterprise AI assistants reach UtilityAI Pro outputs through the internal MCP server and the Energy Analyst agent." },
  "o-fc":    { band: "out", name: "Forecasting & planning", sub: "your load models", kind: "You own",
    desc: "End-use 8760s, adoption trends and propensity scores become inputs to your existing forecasting and capital planning models." },
  "o-derms": { band: "out", name: "DERMS & programs", sub: "DR, managed charging", kind: "You own",
    desc: "Targeted segments and flexible kW estimates feed program implementers, DERMS and marketing platforms." },
  "o-bi":    { band: "out", name: "BI & dashboards", sub: "governed tables", kind: "You own",
    desc: "Any BI tool can read the governed output tables directly, alongside the rest of your enterprise data." },
};

const BANDS = [ // top to bottom
  { id: "out", name: "Apps & agents", tag: "you build and own" },
  { id: "engines", name: "Engines · APIs · MCPs", tag: "answers, delivered anywhere" },
  { id: "models", name: "Core ML models", tag: "26 patents · 38M+ meters" },
  { id: "found", name: "Your data foundation", tag: "your {lakeLabel} + systems of record" },
];

const MODEL_TABS = [
  { id: "disagg", name: "Disaggregation" },
  { id: "attr", name: "Attributes" },
  { id: "ineff", name: "Inefficiency" },
  { id: "life", name: "Lifestyle" },
  { id: "prop", name: "DER propensity" },
  { id: "inc", name: "Income" },
  { id: "pi", name: "Personalized insights" },
  { id: "rev", name: "Revenue loss" },
];

// Published disaggregation accuracy, 15-minute interval data (SOW supplemental materials)
const ACCURACY = [
  { a: "Always On",        days: 30,  p: 100, r: 100, acc: 100, fpr: "0%",   est: 95, pm: 2 },
  { a: "Cooling",          days: 30,  p: 96,  r: 92,  acc: 97,  fpr: "1%",   est: 88, pm: 5 },
  { a: "Heating",          days: 30,  p: 94,  r: 90,  acc: 95,  fpr: "2%",   est: 82, pm: 5 },
  { a: "EV (L2/L3)",       days: 180, p: 85,  r: 92,  acc: 98,  fpr: "<1%",  est: 90, pm: 5 },
  { a: "EV (L1)",          days: 180, p: 65,  r: 75,  acc: 92,  fpr: "<2%",  est: 75, pm: 5 },
  { a: "Pool pump",        days: 150, p: 88,  r: 92,  acc: 96,  fpr: "<1%",  est: 85, pm: 5 },
  { a: "Water heater",     days: 200, p: 90,  r: 85,  acc: 92,  fpr: "3%",   est: 85, pm: 5 },
  { a: "Solar",            days: 90,  p: 99,  r: 98,  acc: 99,  fpr: "0.1%", est: 87, pm: 3 },
  { a: "Lighting",         days: 30,  p: 100, r: 100, acc: 100, fpr: "0%",   est: 75, pm: 5 },
  { a: "Refrigeration",    days: 270, p: 99,  r: 99,  acc: 99,  fpr: "0%",   est: 75, pm: 5 },
];

const W = { b: "Bidgely", u: "Your team / SI", a: "Agent", p: "Platform" };

const USE_CASES = [
  { id: "forecast", group: "Grid & planning", short: "Load forecasting", title: "End-use localized load forecasting",
    tags: ["Grid planning", "Forecasting", "Regulatory"],
    need: "Planners need to know where, when and why load is growing as EVs, heat pumps, cooling and building electrification spread. System forecasts show growth but not which end uses stack into the peak hour of a specific network. Measured end-use evidence makes forecasts defensible to internal and regulatory reviewers.",
    utility: ["AMI interval history", "GIS meter-to-network mapping", "Existing forecast models", "Building permits & housing stock"],
    models: ["Appliance & DER disaggregation", "DER propensity", "Attributes: heat pump, EV charger kW"],
    engines: ["Meter-to-asset aggregation", "Forecast heuristics", "Demand kW processing"],
    access: ["Governed output tables", "Energy Analyst agent", "Analytics Workbench maps"],
    steps: [
      ["Disaggregation writes hourly end-use load for every meter to the governed data layer on each run.", W.b],
      ["Meter-to-asset aggregation joins outputs to your GIS hierarchy and builds 8760 end-use load shapes per transformer, feeder and network.", W.b],
      ["Coincident-peak analysis shows which end uses stack into the hour that sets design criteria, replacing assumed class coincidence factors.", W.b],
      ["Adoption trends and propensity scores feed your short, medium and long-term forecast models as new inputs, next to permits and housing data.", W.u],
      ["Planners and regulatory staff explore results in natural language through the Energy Analyst agent, or on maps in Analytics Workbench.", W.u],
    ],
    value: ["Visibility into EVs, solar, storage, heat pumps and cooling by network", "Forecast assumptions that are transparent and validated", "Evidence for internal and regulatory approval of capital projects"],
    bidgely: ["Models and grid engines in your tenant", "Aggregation recipe for your GIS hierarchy", "Energy Analyst agent"],
    you: ["GIS and forecast model integration", "Feature selection in your forecast models"],
    trace: ["s-ami","s-gis","s-ext","s-wx","d-in","d-out","m-disagg","m-prop","m-attr","e-agg","e-fc","e-kw","d-cdl","i-ea","i-awb","o-fc","o-ai"] },

  { id: "flex", group: "Grid & planning", short: "Flexibility targeting", title: "Load flexibility and VPP targeting",
    tags: ["Demand response", "Managed charging", "VPP"],
    need: "Managed charging, dynamic load management and DR programs pay off only when they enroll customers whose flexible load sits in the right network, is available in the event window and is likely to respond. Broad outreach lowers kW per enrollee and raises acquisition cost.",
    utility: ["Program enrollment & event history", "GIS asset mapping", "DERMS dispatch results", "System and network peaks"],
    models: ["Disaggregation: EV, HVAC, pool, water heating", "Attributes: charger kW, smart thermostat, battery", "Customer lifestyle"],
    engines: ["Flexible load calculation", "Meter-to-asset aggregation", "Demand kW processing"],
    access: ["Analytics Workbench segments", "Governed output tables", "Energy Analyst agent"],
    steps: [
      ["Size each customer's flexible kW hour by hour inside your actual event windows, using disaggregated EV, HVAC and battery load.", W.b],
      ["Rank the population by constrained network and feeder using your GIS mapping.", W.b],
      ["Exclude current participants and join event history and DERMS dispatch results to find under-performers.", W.u],
      ["Publish targeted segments from Analytics Workbench to marketing and program implementers.", W.u],
      ["After events, measure delivered kW per enrollee and quantify dispatchable VPP capacity by network.", W.b],
    ],
    value: ["More flexible kW per enrolled customer", "Lower acquisition cost per delivered kW", "Avoided peak capacity cost and deferred network investment"],
    proof: "NV Energy saw a 2-3x improvement in kW per EV in managed charging by targeting customers with frequent on-peak charging.",
    bidgely: ["Flexible load and aggregation engines", "Analytics Workbench with program simulation"],
    you: ["Event windows and program rules", "DERMS and implementer hand-off"],
    trace: ["s-ami","s-prog","s-gis","s-wx","d-in","d-out","m-disagg","m-attr","m-life","e-flex","e-agg","e-kw","d-cdl","i-awb","i-ea","o-derms","o-bi"] },

  { id: "nws", group: "Grid & planning", short: "Non-wires solutions", title: "Non-wires solution evaluation",
    tags: ["Capital planning", "NWA", "Regulatory"],
    need: "Every load relief project has to answer two questions from staff and intervenors: is the forecast that triggered it real, and was a non-wires option properly evaluated before committing capital. The analysis should be faster and more defensible whether the answer is defer or build.",
    utility: ["Load relief project costs", "Network ratings & design criteria", "GIS topology", "Program cost assumptions"],
    models: ["Appliance & DER disaggregation", "DER propensity", "Appliance & DER attributes"],
    engines: ["Meter-to-asset aggregation", "Flexible load calculation", "Forecast heuristics"],
    access: ["NWS evaluation agent (MCP)", "Energy Analyst agent", "Governed output tables"],
    steps: [
      ["Identify the appliance and DER loads driving forecast growth in each network approaching its design criteria.", W.b],
      ["Quantify shiftable kW behind the affected meters and the eligible customer count for each program option.", W.b],
      ["Combine with your load relief project costs to compare a traditional build with a targeted flexibility portfolio.", W.u],
      ["An agent runs NWA scenarios and returns pre- and post-program 8760 load shapes, eligible customers and projected capacity relief.", W.a],
      ["Planners export results for internal review and regulatory filings.", W.u],
    ],
    value: ["Capital protected with measured end-use evidence of localized growth", "Stronger justification for projects that must proceed", "Deferral or downsizing where flexibility can do the job"],
    bidgely: ["Scenario recipe and agent reference implementation", "Grid engines and model outputs"],
    you: ["Project cost and ratings data", "Filing workflow"],
    trace: ["s-ami","s-gis","s-prog","d-in","d-out","m-disagg","m-prop","m-attr","e-agg","e-flex","e-fc","d-cdl","i-mcp","i-ea","o-ai","o-fc"] },

  { id: "trend", group: "Grid & planning", short: "DER trend monitor", title: "DER and electrification trend monitor",
    tags: ["DER visibility", "Electrification", "Agent"],
    need: "EV, solar, battery and heat pump adoption is uneven, and much of it happens without an interconnection application or program enrollment. Planning and program teams need to see new adoption as it happens, network by network.",
    utility: ["GIS mapping", "Interconnection records", "Program enrollment"],
    models: ["Disaggregation: new EV and solar detection", "Attributes: battery, heat pump, charger kW", "DER propensity"],
    engines: ["Meter-to-asset aggregation", "Forecast heuristics"],
    access: ["Trend monitoring agent", "Analytics Workbench maps", "Energy Analyst agent"],
    steps: [
      ["Each model run flags premises where a new EV, solar array, battery or heat pump appears.", W.b],
      ["Detections are compared with interconnection and program records to surface unreported DERs.", W.u],
      ["Aggregation rolls adoption up by feeder and network and tracks growth month over month.", W.b],
      ["A monitoring agent alerts planners when a network crosses an adoption or load threshold you set.", W.a],
    ],
    value: ["Early warning on localized electrification", "Unreported solar and EV found for interconnection and safety review", "Program outreach to new adopters in their first months"],
    bidgely: ["New-adoption detections every run", "Map layers for EV, solar and LMI"],
    you: ["Interconnection record join", "Alert thresholds and routing"],
    trace: ["s-ami","s-gis","s-prog","d-in","d-out","m-disagg","m-attr","m-prop","e-agg","e-fc","d-cdl","i-ea","i-awb","o-ai","o-bi"] },

  { id: "highbill", group: "Customer experience", short: "High bill", title: "High bill resolution across every channel",
    tags: ["Web & mobile", "IVR", "Chat", "Call center"],
    need: "High bill inquiries arrive through every channel, but customers and agents rarely get a clear, consistent answer about which appliance usage changed. That limits self-service and drives calls, handle time and truck rolls.",
    utility: ["Billing history", "Rate catalog", "Weather", "Customer identity & SSO"],
    models: ["Appliance & DER disaggregation", "Personalized insights", "Appliance inefficiency"],
    engines: ["Rate engine", "Usage & cost aggregations", "Bill projection", "Hyper Insights", "Recommendations"],
    access: ["Full Bill Itemization API", "Analyze My Bill MCP", "IVR Agent MCP", "Energy Assistant MCP"],
    steps: [
      ["At bill close, disaggregation itemizes the bill by appliance. Engines decompose the change against last month and last year across weather, behavior, inefficiency, rate change and billing period length.", W.b],
      ["Promotion pipelines publish the explanation to the application tier behind the APIs and MCP servers.", W.p],
      ["Web and mobile call the Full Bill Itemization API. Chat and IVR agents call the Analyze My Bill and IVR Agent MCP tools.", W.u],
      ["The CSR desktop shows the same explanation before the representative picks up.", W.u],
      ["Every channel returns the same numbers because each one reads the same Complete Data Layer.", W.p],
    ],
    value: ["Fewer high bill calls through self-service and IVR containment", "Shorter average handle time", "Consistent answers and CSAT across channels", "Fewer high bill truck rolls"],
    proof: "APS: 68% CSR utilization of the High Bill Analyzer (88% at summer peak) and a 7% CX score lift on calls that used it.",
    bidgely: ["CX engines, APIs and MCP servers", "Reference widgets and agent tools as source code"],
    you: ["Portal, IVR and CSR integration", "Auth, API gateway and brand"],
    trace: ["s-ami","s-bill","s-rate","s-wx","d-in","d-out","m-disagg","m-pi","m-ineff","e-rate","e-cost","e-bp","e-hi","e-rec","d-cdl","d-promo","i-api","i-mcp","o-web","o-ivr","o-chat","o-csr"] },

  { id: "alert", group: "Customer experience", short: "High bill alert", title: "Proactive high bill alert",
    tags: ["Email", "Alerts", "Reference recipe"],
    need: "Customers should hear that a bill is trending high while there is still time to act. The alert explains the likely cause and gives savings tips for the appliances driving it.",
    utility: ["Month-to-date AMI", "Rate catalog", "Bill cycle calendar", "Email distribution platform"],
    models: ["Disaggregation, month-to-date"],
    engines: ["Bill projection", "Rate engine", "Recommendations", "Hyper Insights"],
    access: ["Bill Projection API", "My Recommendations API", "Control Center thresholds"],
    steps: [
      ["When the first AMI day of a new cycle arrives, a PySpark job computes the baseline projection: a kWh forecast for the cycle, priced by the Rate engine.", W.b],
      ["At checkpoints, for example days 10, 15 and 20, the projection is recomputed with usage accumulated so far.", W.b],
      ["If the new projection exceeds the baseline by a configurable threshold such as 50%, the account is tagged eligible. Thresholds are set in the Control Center.", W.p],
      ["The email job pulls the projection, the month-to-date appliance itemization and the top tips for those appliances into the template.", W.b],
      ["Your email platform sends the alert. The same payload can drive an in-app banner.", W.u],
    ],
    value: ["Customers can act before the bill arrives", "Fewer bill-shock calls", "Tips tied to the appliance actually driving the increase"],
    bidgely: ["Projection and checkpoint pipelines", "Email payload and template sample"],
    you: ["Template design and send", "Threshold policy"],
    trace: ["s-ami","s-rate","s-bill","d-in","d-out","m-disagg","e-bp","e-rate","e-rec","e-hi","d-cdl","d-promo","i-api","i-cc","o-email","o-web"] },

  { id: "rates", group: "Customer experience", short: "Rate coaching", title: "TOU rate coaching and best rate",
    tags: ["Time-of-use", "Load shift", "Email", "Agent"],
    need: "Time-varying rates and load-shift programs work when customers can see which appliances fall in the peak window, what moving them would save and which rate fits their home.",
    utility: ["Rate catalog & TOU windows", "Billing history", "Your rate engine (optional)", "Rate enrollment records"],
    models: ["Disaggregation, hourly", "Customer lifestyle", "Attributes: EV, pool, water heater"],
    engines: ["Rate engine", "Rate comparison", "Usage & cost aggregations", "Recommendations"],
    access: ["Rate Comparison API", "TOU Bill Saving Insight API", "Find the Best Rate MCP", "Analytics Workbench TOU targeting"],
    steps: [
      ["Hourly disaggregation shows which end uses fall inside each customer's peak window and how much is realistically shiftable.", W.b],
      ["Rate comparison projects the bill on each eligible plan and the effect of moving specific appliances. Use the Bidgely Rate engine or connect your own.", W.b],
      ["Rank the base by projected savings so each rate goes to the customers most likely to benefit and stay enrolled.", W.u],
      ["Deliver coaching through web, mobile, monthly summary emails, chat and the Find the Best Rate tool.", W.u],
    ],
    value: ["Higher TOU enrollment and retention", "More on-peak load shifted per customer", "Shifted load that counts as flexible capacity in the network"],
    proof: "PSEG Long Island moved ~900k residential customers to Time-of-Day rates with 98% retention.",
    bidgely: ["Rate, comparison and TOU engines", "Monthly summary and coaching content"],
    you: ["Rate catalog upkeep", "Channel integration"],
    trace: ["s-ami","s-rate","s-bill","s-prog","d-in","d-out","m-disagg","m-life","m-attr","e-rate","e-rc","e-cost","e-rec","d-cdl","d-promo","i-api","i-mcp","i-awb","o-web","o-email","o-chat"] },

  { id: "assistant", group: "Customer experience", short: "Energy Assistant", title: "Energy Assistant with EV and solar what-ifs",
    tags: ["Chat", "MCP", "Agentic tools"],
    need: "Customers ask about bills, usage and savings in chat and expect answers grounded in their own data. A general-purpose chatbot cannot explain a specific home.",
    utility: ["Customer identity & SSO", "Rates, including EV plans", "Program catalog", "Your agent platform"],
    models: ["Disaggregation", "Personalized insights", "DER propensity", "Attributes"],
    engines: ["Rate engine", "Rate comparison", "Bill projection", "Recommendations", "Hyper Insights"],
    access: ["Energy Assistant MCP", "Agentic Tools MCP: EV ROI, PV ROI, Best Rate", "Home Bill Optimizer MCP"],
    steps: [
      ["Your customer-facing agent on {agentsExt} authenticates the customer and resolves the meter.", W.u],
      ["It calls Bidgely MCP tools as a sub-agent for bill clarification, consumption breakdown and savings guidance.", W.a],
      ["When intent to buy an EV or install solar comes up, the EV ROI or PV ROI tool simulates cost and payback on the customer's actual usage and eligible rates.", W.a],
      ["The Home Bill Optimizer builds a downloadable savings plan: 12-month history, appliance breakdown, recommendations and program offers.", W.a],
      ["Evals, guardrails and brand voice stay in your agent platform.", W.u],
    ],
    value: ["Contact deflection with answers grounded in the customer's data", "Qualified entry point into EV and solar programs", "A utility-branded alternative to third-party solar estimates"],
    bidgely: ["MCP servers and tool definitions", "Reference agent implementation"],
    you: ["Agent host, evals and guardrails", "Sub-agent routing"],
    trace: ["s-ami","s-bill","s-rate","s-prog","d-in","d-out","m-disagg","m-pi","m-prop","m-attr","e-rate","e-rc","e-bp","e-rec","e-hi","d-cdl","d-promo","i-mcp","o-chat","o-web"] },

  { id: "web", group: "Customer experience", short: "Appliance breakdown", title: "Appliance breakdown on web and mobile",
    tags: ["Web & mobile", "Reference recipe"],
    need: "Customers who understand what drives their usage engage with every other program. They need appliance, cost and usage views across year, month and day.",
    utility: ["Customer portal & SSO", "Billing and rates"],
    models: ["Appliance & DER disaggregation"],
    engines: ["Usage & cost aggregations", "Rate engine"],
    access: ["Energy Details Charts Data API", "Energy Usage API"],
    steps: [
      ["The customer opens energy details in your portal. The portal authenticates through SSO and resolves customer to meter.", W.u],
      ["The page requests the selected view (appliance, cost or usage by year, month or day) from the Energy Details Charts Data API.", W.u],
      ["Nothing is computed at request time. Disaggregation itemizes at each bill close, the engines produce cost views and rollups, and promotion pipelines publish them.", W.p],
      ["The portal renders the chart in your brand, starting from Bidgely reference widgets.", W.u],
    ],
    value: ["Fast, web-scale responses", "One set of numbers across web, email and agents", "The foundation for every other engagement feature"],
    bidgely: ["Charts Data API and reference widget", "Aggregation pipelines"],
    you: ["Front-end design", "Portal integration"],
    trace: ["s-ami","s-bill","s-rate","d-in","d-out","m-disagg","e-cost","e-rate","d-cdl","d-promo","i-api","o-web"] },

  { id: "targeting", group: "Analytics & programs", short: "Program targeting", title: "Program targeting for EE, DR and income-qualified",
    tags: ["DSM", "Marketing", "Analytics Workbench"],
    need: "Program teams spend budget on broad outreach because they cannot see who owns which appliance, whose equipment is failing or who likely qualifies for assistance.",
    utility: ["Program participation & events", "Up to 10 custom data fields", "Marketing platform"],
    models: ["Attributes: heating fuel, heat pump, thermostat", "Appliance inefficiency", "Customer income", "Customer lifestyle", "DER propensity"],
    engines: ["Usage & cost aggregations"],
    access: ["Analytics Workbench", "Program simulation", "CSV and PDF export"],
    steps: [
      ["Analysts build segments in Analytics Workbench, for example electric resistance heat, no heat pump, likely income-qualified and high winter bills.", W.u],
      ["Program simulation estimates participation, load impact and savings before launch.", W.b],
      ["Current participants are excluded using your program history.", W.u],
      ["Segments are saved, published and exported to campaign tools and implementers.", W.u],
    ],
    value: ["Lower DSM delivery cost through precise qualification", "More savings per participant", "Income-qualified households found at premise level, not census-block averages"],
    bidgely: ["Analytics Workbench, delivered by Bidgely", "Model outputs as segmentation fields"],
    you: ["Program rules", "Campaign execution"],
    trace: ["s-ami","s-prog","s-ext","d-in","d-out","m-attr","m-ineff","m-inc","m-life","m-prop","e-cost","d-cdl","i-awb","i-ea","o-bi","o-derms"] },

  { id: "analyst", group: "Analytics & programs", short: "Energy Analyst", title: "Energy Analyst agent for every department",
    tags: ["GenAI", "Internal MCP", "Self-service analytics"],
    need: "Analysts, load research and regulatory staff have ad-hoc questions that do not justify building a dashboard.",
    utility: ["Your data catalog", "Your internal AI tools", "Other enterprise data sets"],
    models: ["All model outputs"],
    engines: ["All engine outputs"],
    access: ["Energy Analyst agent", "Internal MCP server"],
    steps: [
      ["A user asks a plain-language question, such as how many homes in a network added an EV this year.", W.u],
      ["The agent translates it into governed queries over the Complete Data Layer, under your access controls.", W.a],
      ["It returns an explained, data-grounded answer along with the query it ran.", W.a],
      ["Through the internal MCP server, the same capability plugs into {agentsInt} and your other AI tools.", W.u],
    ],
    value: ["Answers in minutes instead of analyst tickets", "Model outputs open to every department", "Joins with the rest of your governed data"],
    bidgely: ["Energy Analyst agent, delivered by Bidgely", "Internal MCP server"],
    you: ["Access policies", "Enterprise AI tool connection"],
    trace: ["s-ami","s-gis","s-prog","d-out","m-disagg","m-prop","m-inc","e-agg","d-cdl","i-ea","i-mcp","o-ai"] },

  { id: "revenue", group: "Analytics & programs", short: "Revenue protection", title: "Revenue protection",
    tags: ["Theft", "Tamper", "Field operations"],
    need: "Theft, tampering and rate misuse cost revenue and create safety risk. Investigators need a short, ranked list with a reason for each case.",
    utility: ["Meter events & flags", "Billing & rate assignment", "Field investigation outcomes"],
    models: ["Revenue loss", "Disaggregation"],
    engines: ["Demand kW processing"],
    access: ["Governed output tables", "Analytics Workbench"],
    steps: [
      ["The revenue loss model scans consumption for anomalies and categorizes each one: theft, rate misuse, tampering, load violation, power factor or terminal burn.", W.b],
      ["Cases are ranked and joined with meter events and rate assignment.", W.u],
      ["Field investigation outcomes feed back to tune thresholds.", W.u],
    ],
    value: ["Recovered revenue", "Fewer wasted field visits", "Early detection of terminal burn and other safety issues"],
    bidgely: ["Revenue loss model", "Case output tables"],
    you: ["Investigation workflow", "Outcome feedback"],
    trace: ["s-ami","s-bill","d-in","d-out","m-rev","m-disagg","e-kw","d-cdl","i-awb","o-bi"] },
];

const TRACE_CHIPS = ["forecast", "flex", "nws", "highbill", "rates", "assistant", "targeting", "analyst"];

const SECURITY = [
  { ic: "lock", h: "Encrypted models on confidential compute", p: "Model images are encrypted and run on attested confidential-computing hardware. Keys are released only to verified workloads, which protects your data end to end." },
  { ic: "db", h: "Customer data never leaves", p: "Inputs are read from your data platform and outputs are written back as governed tables in your catalog. All processing runs inside your tenant." },
  { ic: "key", h: "Your identity, gateway and guardrails", p: "APIs and MCP servers sit behind your customer SSO and API gateway. Agents run on your platform with your evals and controls." },
  { ic: "check", h: "Model quality you can audit", p: "Each model is validated against your ground truth before launch, regression tested on every version, and published with accuracy tables and methodology." },
  { ic: "arrow", h: "Minimal, documented egress", p: "Only the key-release attestation handshake and operational counts cross the boundary, over {network}. No PII and no consumption data." },
];

const GANTT = [
  { name: "Define", sub: "scope, data architecture, plan", s: -2, e: 0, cls: "soft", lbl: "Joint" },
  { name: "Launch A", sub: "core models + Analytics Workbench", s: 0, e: 4, cls: "", lbl: "Bidgely" },
  { name: "Launch B & C", sub: "remaining models + Energy Analyst", s: 2, e: 7, cls: "", lbl: "Bidgely" },
  { name: "Data layer & CX APIs", sub: "engines, APIs, MCP, Control Center", s: 1, e: 9, cls: "", lbl: "Bidgely" },
  { name: "Use case design", sub: "channels, agents, analytics", s: 3, e: 8, cls: "soft", lbl: "Joint design" },
  { name: "Use case build & launch", sub: "you or your SI, Bidgely support", s: 8, e: 14, cls: "util", lbl: "Your team / SI" },
];
